version: '3'

services:
  rtsp-server:
    build: ./rtsp-server
    networks:
      - app-network
    ports:
      - "8554:8554"
  camera-simulator:
    build: ./camera-simulator
    networks:
      - app-network
    depends_on:
      - rtsp-server
networks:
  app-network:
    driver: bridge
